Document: someplayer
Title: Debian someplayer Manual
Author: <insert document author here>
Abstract: This manual describes what someplayer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/someplayer/someplayer.sgml.gz

Format: postscript
Files: /usr/share/doc/someplayer/someplayer.ps.gz

Format: text
Files: /usr/share/doc/someplayer/someplayer.text.gz

Format: HTML
Index: /usr/share/doc/someplayer/html/index.html
Files: /usr/share/doc/someplayer/html/*.html

  
